import Head from "next/head";
import CommunitySection from "../sections/CommunitySection/CommunitySection";
import HomeSection from "../sections/Home/HomeSection";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<HomeSection />
				<CommunitySection />
			</main>

			<footer />
		</div>
	);
}
